apiVersion: v1
kind: Service
metadata:
  name: easytravel-frontend
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: easytravel-frontend
