apiVersion: v1
kind: Service
metadata:
  name: easytravel-backend
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      nodePort: 30687
  selector:
    app: easytravel-backend
