apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  creationTimestamp: null
  name: easytravel-frontend
spec:
  host: easytravel-frontend.easytravel-production.svc.cluster.local
