apiVersion: v1
kind: Service
metadata:
  name: easytravel-loadgen
spec:
  type: LoadBalancer
  ports:
    - name: "89"
      port: 89
      targetPort: 89
  selector:
    app: easytravel-loadgen
